name: BasicEssentials
main: me.LiamPlugin.BasicEssentialsMain
author: [DUFC_Liam]
authors: [IllX]
version: 1.1.0
commands:
   exp:
      description: Shows you how much EXP you currently have.
      usage: /<command>
   exptolevelup:
      description: Shows you how much EXP to the next level.
      usage: /<command>
   expclear:
      description: Clears all your EXP
      usage: /<command>
   expheal:
      description: Heals you for 1 EXP level.
      usage: /<command>
   expfeed:
      description: Feeds you for 1 EXP level.
      usage: /<command>
